# Generated by Django 3.0 on 2021-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
