# Generated by Django 3.0 on 2021-01-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghatakcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBitmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.TextField(blank=True, db_column='FieldName', null=True)),
                ('datatypes', models.CharField(blank=True, db_column='DataTypes', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Django_Bitmap',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
